# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CrashCollectDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'SSZipArchive' ,:path=>'~/Downloads/ZipArchive'
  # Pods for CrashCollectDemo

  target 'CrashCollectDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CrashCollectDemoUITests' do
    # Pods for testing
  end

end
